### ISSUE TITLE
Great work! :) - I have some questions about your memwallet

### ISSUE THREAD

**Issue by patoshii** [dvdbng/memwallet#1]
Hi David,

Great job on the memwallet. I've always wanted to figure out how to generate other coins using the warpwallet setup. I'm still learning how this all works and trying to wrap my head around it as I'm not a js ninja like you. 

I've been poking around to see how it works. Below is the code that setups the difficulty of the scrypt with Math.pow. My question is does it have to be a Math.pow() ? Why can't you just put any number in there? I tried it with scrypt(), but it throws an error as it needs to be the power of 2. It works for pbkdf2 with any number in there, but I dont understand why it has to be to the 2^N power. Be great if you can explain it.

```
  scrypt(Buffer.concat([password_buffer, x1]), Buffer.concat([salt_buffer, x1]), Math.pow(2, power), 8, 1, 32, function(error, progress, key1) {
    if(key1) {
      pbkdf2.pbkdf2(Buffer.concat([password_buffer, x2]), Buffer.concat([salt_buffer, x2]), Math.pow(2, 16), 32, 'sha256', function(err, key2) {

```

Thanks!

**Comment by dvdbng** [comment]
Because the scrypt algorithm requires the parameter to be a power of 2: https://tools.ietf.org/html/rfc7914#section-2 You can find another answer here: https://crypto.stackexchange.com/questions/15674/is-there-a-reason-that-the-n-value-in-scrypt-is-limited-to-powers-of-two

**Comment by dvdbng** [comment]
Also keep in mind changing the difficulty values changes the generated seed, so it's highly discouraged (you need to remember your passphrase, salt AND difficulty parameters)
